import User from "../../assets/images/tayab.jpg";
import { GridColDef } from "@mui/x-data-grid";
import { Box } from "@mui/material";
import styles from "../ClaimListData/styles.module.scss";

export interface ClaimListTypes {
    id: number;
    image: any;
    name: string;
    price: string;
    labelToken: string;
    tokenNumber: string;
}

const rows: ClaimListTypes[] = [
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 1,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 2,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 3,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 4,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 5,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
    {
        id: 6,
        image: User,
        name: "Tayyab",
        price: "Price : 1 USDT",
        labelToken: "Claimable tokens",
        tokenNumber: "10.0",
    },
];
const columns: GridColDef[] = [
    {
        field: "name",
        headerName: "Name",
        width: 300,
        headerClassName: "column-header-name",
        cellClassName: "column-cell-name",
        renderCell: (params) => (
            <>
                <Box className={styles.nameColImg}>
                    <img src={params.row.image} alt={params.row.name} />
                </Box>
                <Box className={styles.nameColText}>
                    <p>{params.row.name}</p>
                    <p>{params.row.price}</p>
                </Box>
            </>
        ),
    },
    {
        field: "labelToken",
        headerName: "Token",
        width: 300,
        headerClassName: "column-header-token",
        cellClassName: "column-cell-token",
        renderCell: (params) => (
            <>
                <div className={styles.TokenColText}>
                    <p>{params.row.labelToken}</p>
                    <p>{params.row.tokenNumber}</p>
                </div>
            </>
        ),
    },
    {
        field: "labelToken",
        headerName: "Token",
        width: 300,
        headerClassName: "column-header-token",
        cellClassName: "column-cell-token",
        renderCell: (params) => (
            <>
                <div className={styles.TokenColText}>
                    <p>{params.row.labelToken}</p>
                </div>
            </>
        ),
    },
    {
        field: "action",
        headerName: "Action",
        headerClassName: "column-header-action",
        cellClassName: "column-cell-action",
        width: 150,
        renderCell: (params) => (
            <>
                <div className={styles.ActionCol}>
                    <button>Claim</button>
                </div>
            </>
        ),
    },
];

export { rows, columns };
